"""
Generates a clean PDF from BRD session data.

Uses reportlab — pure Python, no external dependencies.
The PDF is generated in-memory (no temp files) and returned as bytes.
"""

from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

# Colors matching Vellum's dark theme (used for accents in PDF)
BLUE = HexColor("#3b82f6")
DARK = HexColor("#09090b")
ZINC = HexColor("#27272a")
TEXT = HexColor("#18181b")


def generate_brd_pdf(session_data: dict) -> bytes:
    """Generate a PDF from a session dict. Returns PDF bytes."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm,
                            topMargin=20*mm, bottomMargin=20*mm)

    styles = getSampleStyleSheet()
    brd = session_data.get("brd", {})

    # Custom styles
    styles.add(ParagraphStyle("Title2", parent=styles["Title"], fontSize=22,
                               textColor=BLUE, spaceAfter=4*mm, spaceBefore=0))
    styles.add(ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14,
                               textColor=HexColor("#1e40af"), spaceBefore=6*mm, spaceAfter=2*mm))
    styles.add(ParagraphStyle("Body2", parent=styles["Normal"], fontSize=10,
                               textColor=TEXT, leading=15, spaceAfter=2*mm))
    styles.add(ParagraphStyle("Small", parent=styles["Normal"], fontSize=9,
                               textColor=HexColor("#52525b"), leading=13))

    elements = []

    # ── Cover ────────────────────────────────────────────────────
    name = session_data.get("startup_name", "Startup")
    elements.append(Paragraph(name, styles["Title2"]))
    elements.append(Paragraph("Business Requirements Document", styles["H2"]))
    elements.append(Paragraph("Generated by Vellum AI", styles["Small"]))

    if session_data.get("vellum_score"):
        elements.append(Spacer(1, 3*mm))
        elements.append(Paragraph(
            f"<b>Vellum Score: {session_data['vellum_score']}/10</b>",
            ParagraphStyle("Score", parent=styles["Normal"], fontSize=12, textColor=BLUE)
        ))

    elements.append(HRFlowable(width="100%", thickness=1, color=ZINC, spaceAfter=5*mm, spaceBefore=3*mm))

    # ── Executive Summary ────────────────────────────────────────
    if brd.get("executive_summary"):
        elements.append(Paragraph("Executive Summary", styles["H2"]))
        elements.append(Paragraph(brd["executive_summary"], styles["Body2"]))

    # ── Problem Statement ────────────────────────────────────────
    ps = brd.get("problem_statement", {})
    if isinstance(ps, dict):
        elements.append(Paragraph("Problem Statement", styles["H2"]))
        if ps.get("current_situation"):
            elements.append(Paragraph(f"<b>Current Situation:</b> {ps['current_situation']}", styles["Body2"]))
        if ps.get("pain_points"):
            for pp in ps["pain_points"]:
                elements.append(Paragraph(f"  • {pp}", styles["Body2"]))
        if ps.get("impact"):
            elements.append(Paragraph(f"<b>Impact:</b> {ps['impact']}", styles["Body2"]))
    elif isinstance(ps, str) and ps:
        elements.append(Paragraph("Problem Statement", styles["H2"]))
        elements.append(Paragraph(ps, styles["Body2"]))

    # ── Objectives ───────────────────────────────────────────────
    objectives = brd.get("objectives", [])
    if objectives:
        elements.append(Paragraph("Objectives", styles["H2"]))
        for obj in objectives:
            elements.append(Paragraph(f"  • {obj}", styles["Body2"]))

    # ── Scope ────────────────────────────────────────────────────
    scope = brd.get("scope", {})
    if isinstance(scope, dict) and (scope.get("in_scope") or scope.get("out_of_scope")):
        elements.append(Paragraph("Scope", styles["H2"]))
        for item in scope.get("in_scope", []):
            elements.append(Paragraph(f"  <font color='green'>✓</font> {item}", styles["Body2"]))
        for item in scope.get("out_of_scope", []):
            elements.append(Paragraph(f"  <font color='red'>✗</font> {item}", styles["Body2"]))

    # ── Stakeholders ─────────────────────────────────────────────
    stakeholders = brd.get("stakeholders", [])
    if stakeholders:
        elements.append(Paragraph("Stakeholders", styles["H2"]))
        table_data = [["Role", "Responsibility"]]
        for s in stakeholders:
            table_data.append([s.get("role", ""), s.get("responsibility", "")])
        t = Table(table_data, colWidths=[40*mm, 120*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, ZINC),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)

    # ── Functional Requirements ──────────────────────────────────
    frs = brd.get("functional_requirements", [])
    if frs:
        elements.append(Paragraph("Functional Requirements", styles["H2"]))
        table_data = [["ID", "Requirement", "Priority"]]
        for fr in frs:
            table_data.append([fr.get("id", ""), fr.get("requirement", ""), fr.get("priority", "")])
        t = Table(table_data, colWidths=[20*mm, 110*mm, 25*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, ZINC),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(t)

    # ── User Stories ─────────────────────────────────────────────
    stories = brd.get("user_stories", [])
    if stories:
        elements.append(Paragraph("User Stories", styles["H2"]))
        for s in stories:
            elements.append(Paragraph(
                f"<b>{s.get('id', '')}</b> — As a <i>{s.get('as_a', '')}</i>, "
                f"I want <i>{s.get('i_want', '')}</i>, so that <i>{s.get('so_that', '')}</i>",
                styles["Body2"]
            ))

    # ── Technical Architecture ───────────────────────────────────
    ta = brd.get("technical_architecture", {})
    if isinstance(ta, dict) and ta.get("overview"):
        elements.append(Paragraph("Technical Architecture", styles["H2"]))
        elements.append(Paragraph(ta["overview"], styles["Body2"]))
        if ta.get("tech_stack"):
            elements.append(Paragraph(f"<b>Tech Stack:</b> {', '.join(ta['tech_stack'])}", styles["Body2"]))

    # ── SWOT ─────────────────────────────────────────────────────
    swot = brd.get("swot", {})
    if isinstance(swot, dict) and any(swot.values()):
        elements.append(Paragraph("SWOT Analysis", styles["H2"]))
        for label, key in [("Strengths", "strengths"), ("Weaknesses", "weaknesses"),
                           ("Opportunities", "opportunities"), ("Threats", "threats")]:
            items = swot.get(key, [])
            if items:
                elements.append(Paragraph(f"<b>{label}:</b>", styles["Body2"]))
                for item in items:
                    elements.append(Paragraph(f"  • {item}", styles["Body2"]))

    # ── Risks ────────────────────────────────────────────────────
    risks = brd.get("risks", [])
    if risks:
        elements.append(Paragraph("Risks & Mitigations", styles["H2"]))
        table_data = [["Risk", "Probability", "Impact", "Mitigation"]]
        for r in risks:
            table_data.append([r.get("risk", ""), r.get("probability", ""),
                               r.get("impact", ""), r.get("mitigation", "")])
        t = Table(table_data, colWidths=[40*mm, 25*mm, 20*mm, 75*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, ZINC),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(t)

    # ── Timeline ─────────────────────────────────────────────────
    timeline = brd.get("timeline", [])
    if timeline:
        elements.append(Paragraph("Timeline", styles["H2"]))
        for phase in timeline:
            elements.append(Paragraph(
                f"<b>{phase.get('phase', '')}</b> — {phase.get('duration', '')}",
                styles["Body2"]
            ))
            for d in phase.get("deliverables", []):
                elements.append(Paragraph(f"  • {d}", styles["Small"]))

    # ── Validation Summary ───────────────────────────────────────
    val = session_data.get("validation")
    if isinstance(val, dict) and val.get("overall_score"):
        elements.append(Paragraph("Idea Validation Summary", styles["H2"]))
        elements.append(Paragraph(
            f"<b>Score:</b> {val['overall_score']}/10 | <b>Verdict:</b> {val.get('verdict', '').replace('_', ' ').title()}",
            styles["Body2"]
        ))
        elements.append(Paragraph(val.get("recommendation", ""), styles["Body2"]))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer.read()